### ISSUE TITLE
Repair compilation with clang

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sparsehash/sparsehash#103]
```
What steps will reproduce the problem?
1.  set CC=clang
2.  attempt to build


What is the expected output? What do you see instead?
Source should build

What version of the product are you using? On what operating system?
2.0.2 on FreeBSD Current

Please provide any additional information below.

I've attached the buildfailure log from the freebsd port and the patch we've 
applied to fix this.
```

Original issue reported on code.google.com by `seanwbr...@gmail.com` on 15 Sep 2014 at 3:46

Attachments:
* [patch-src__sparsehash__internal__sparsehashtable.h](https://storage.googleapis.com/google-code-attachments/sparsehash/issue-103/comment-0/patch-src__sparsehash__internal__sparsehashtable.h)
* [google-sparsehash-clang.txt](https://storage.googleapis.com/google-code-attachments/sparsehash/issue-103/comment-0/google-sparsehash-clang.txt)

**Comment by donovanhide** [comment]
Should be fixed in:

https://github.com/sparsehash/sparsehash/releases/tag/sparsehash-2.0.3
