### ISSUE TITLE
Installation fails at "make" step on Red Hat Linux 6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sparsehash/sparsehash#105]
```
What steps will reproduce the problem?
1.unpack from .tar.gz
2../configure --prefix=<local directory> 
3.make

What is the expected output? What do you see instead?
expected: make finishes without error, subsequent make check passes all tests
observed: make aborts with error code 2; make check does not pass tests

What version of the product are you using? On what operating system?

sparsehash version = 2.0.2
OS = Red Hat Enterprise Linux Server release 6.6 (Santiago)

Please provide any additional information below.

output from 'make' and 'make check' attached as text files.




```

Original issue reported on code.google.com by `jo...@dsmz.de` on 13 Jan 2015 at 10:29

Attachments:
* [output_make.txt](https://storage.googleapis.com/google-code-attachments/sparsehash/issue-105/comment-0/output_make.txt)
* [output_make_check.txt](https://storage.googleapis.com/google-code-attachments/sparsehash/issue-105/comment-0/output_make_check.txt)

**Comment by Dekken** [comment]
Is GCC 4.4 supported? I've built on AWS RHEL with 4.9+, and this does not happen.

**Comment by Dekken** [comment]
That libunwind warning is probably the reason for undefined reference errors.
