### ISSUE TITLE
make check fails with GCC 4.9 on Mac OS 10.10.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sparsehash/sparsehash#106]
```
What steps will reproduce the problem?
brew install google-sparsehash --cc=gcc-4.9 --build-from-source

What is the expected output? What do you see instead?
Success.

What version of the product are you using? On what operating system?
sparsehash 2.0.2
Mac OS 10.10.1

Please provide any additional information below.

```
Running HashtableDeathTest.InsertSizeTypeOverflow
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_fill_insert
/bin/sh: line 1: 71227 Abort trap: 6           ${dir}$tst
FAIL: hashtable_test
```

Complete logs:
❯❯❯ brew gist-logs google-sparsehash --cc=gcc-4.9 --build-from-source -v
https://gist.github.com/5a6b10ab7ba0e0f8402f
```

Original issue reported on code.google.com by `sjackman` on 26 Jan 2015 at 6:26

**Comment by Dekken** [comment]
Pretty sure this is fixed, trying to track down the commit. I had a problem on OSX until I updated to 2.0.3

**Comment by Dekken** [comment]
Please try with 2.0.3.

Comment if it comes up again.
