### ISSUE TITLE
Is it thread safe for insertion of sparse hash table?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sparsehash/sparsehash#108]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `iubw...@gmail.com` on 9 Mar 2015 at 8:27

**Comment by Dekken** [comment]
Mark closed.

**Comment by Dekken** [comment]
It's feasible that it could know about all threads and it being thread safe, but I doubt that is the case. Seems like a lot of over head for a situation that may not be necessary.
