### ISSUE TITLE
Build error on OS X 10.11 El Capitan (public beta)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sparsehash/sparsehash#111]
```
Fails to build (using either MacPorts or Homebrew) on OS X 10.11 Beta 
(15A243d), Xcode Version 7.0 beta 5 (7A176x)

More info on other trackers:
- https://trac.macports.org/ticket/48556
- https://github.com/Homebrew/homebrew/issues/41087

The homebrew issue suggests a fix, but looks like it could break on other 
platforms.

Build errors in attached log
```

Original issue reported on code.google.com by `and...@thefrog.net` on 12 Aug 2015 at 5:06

Attachments:
* [main.log](https://storage.googleapis.com/google-code-attachments/sparsehash/issue-111/comment-0/main.log)

**Comment by pclinger** [comment]
Hello, is there any update on this issue?

**Comment by donovanhide** [comment]
Seems like the previous comment was deleted, but there is a branch which could do with some testing on your OS:

https://github.com/sparsehash/sparsehash/tree/issue-fixes

**Comment by manuelRiel** [comment]
Just tried compiling this together with or-tools on Mac OSX 10.10.5 and the `issue-fixes` branch worked fine. Thanks for the fix.

**Comment by JosephRedfern** [comment]
Fix worked to me, too. Thanks.

**Comment by donovanhide** [comment]
Great, will merge soon and do a new tagged release.

**Comment by rdp** [comment]
Looking forward to it here  :+1:

**Comment by donovanhide** [comment]
Sorry for the long delay, should all be fixed in:

https://github.com/sparsehash/sparsehash/releases/tag/sparsehash-2.0.3
