### ISSUE TITLE
Can you create a tag  2.0.2

### ISSUE THREAD

**Issue by lperron** [sparsehash/sparsehash#112]
The code is stable :-)
Can you tag the current branch with the v2.0.2 tag

**Comment by donovanhide** [comment]
That's done!

https://github.com/sparsehash/sparsehash/tree/sparsehash-2.0.2

Can you check it works for your needs?

**Comment by lperron** [comment]
Perfect!

Thanks

Laurent Perron | Operations Research | lperron@google.com | (33) 1 42 68 53
00


2015-09-03 13:12 GMT+02:00 Donovan Hide <notifications@github.com>:
