### ISSUE TITLE
Is there any current issues to be worked on the sparsehash / densehash structures?

### ISSUE THREAD

**Issue by pyrobit** [sparsehash/sparsehash#113]
Hi there,

I checked this code description and in 2005 it informed "It would be nice to rework this C class to follow the C++ API as closely as possible (eg have a set_deleted_key() instead of using a #define like this code does now).  I believe the code compiles and runs, if anybody is interested in using it now, but it's subject to major change in the future, as people work on it. Craig Silverstein"

I would like to check if this set_deleted_key() issue was resolved, else what are the current issues. 
(I am looking for a theme to work in software engineering monography.)
thanks!

**Comment by donovanhide** [comment]
Hi,

most of the current issues are present here on Github in the issue-tracker :-) Some of them have been addressed in this branch which needs to be merged:

https://github.com/sparsehash/sparsehash/tree/issue-fixes

There's also a fork here:

https://github.com/sparsehash/sparsehash-c11

which aims to remove all the type traits and conditional build logic that isn't required now that C++11 is widely available. Ideally, it needs a better build process (CMake or plain old Makefile).

Patches and contributions are more than welcome. This project has been static for some time :-)

Cheers,
Donovan.
