### ISSUE TITLE
Windows - use unordered_map

### ISSUE THREAD

**Issue by Dekken** [sparsehash/sparsehash#116]
It complains otherwise.

I've done it here:
https://github.com/mkn/google.sparsehash/blob/master/src/windows/config.h

**Comment by Dekken** [comment]
This script does the include copy/setup for windows if you need it:
https://github.com/mkn/google.sparsehash/blob/master/mkn.bat

**Comment by donovanhide** [comment]
Can you be more specific? For a particular version of Visual Studio? Are some `_MSC_VER` conditionals required? I don't have access to a Windows machine unfortunately, but a tested pull request would be gratefully received :-)

**Comment by Dekken** [comment]
Sure, sorry, it's an error without the define since VS15
    
error C2338: <hash_map> is deprecated and will be REMOVED. Please use <unordered_map>. You can define _SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS to acknowledge that you have received this
warning.

Unordered map compiles under 12/13, but I can't attest for anything older

**Comment by donovanhide** [comment]
Sounds like possibly a `#if _MSC_VER>=1900` clause is required, or possibly `#if _MSC_VER == 1700`?

Either way, a pull request will be accepted :-)

**Comment by donovanhide** [comment]
Fixed in 804c039c10af1c7a130422735ef7cbf4a7bf2663
