### ISSUE TITLE
sparse_hash_map serializer/deserializer

### ISSUE THREAD

**Issue by MitchesD** [sparsehash/sparsehash#121]
Hey there,
I have a question if it's possible to serializer/deserialize sparse_hash_map which consist of
```cpp
sparse_hash_map<unsigned long long, std::vector<Structure>>
```

I tried to write my own serializer, but it seems it's not possible to serialize STL containers, did I miss something or simply I can't write any serializer for this map?

**Comment by Dekken** [comment]
I believe sparse_hash uses the STL underneath so I think it would be unlikely that this would work.

See: https://github.com/sparsehash/sparsehash/blob/master/src/windows/config.h

It may be a windows config, but it's roughly the same as the non-windows config is generated by ./configure

**Comment by MitchesD** [comment]
So you think that there is no way how to do that?

**Comment by Dekken** [comment]
I was going by what you had said regarding STL, however boost can supposedly serialise STL containers, so perhaps have a look at that. Personally I would look at protocol buffers first, only because I avoid boost when possible

**Comment by MitchesD** [comment]
I am on ubuntu, problem also is that configure doesn't use std::unordered_map but still C++03 version. Any idea what could be wrong? Have GCC 5.3.1

**Comment by Dekken** [comment]
Could you pastebin your the config.h?

Perhaps try the C++11 version here, which has no configure requirement. 
https://github.com/sparsehash/sparsehash-c11

**Comment by MitchesD** [comment]
Will try that C++11 version, thank you, I will post there config and provide more info if that experimental C++11 won't be working :)

**Comment by MitchesD** [comment]
Even with that version, I can't use boost on that, maybe somewhere deeper it's based on unordered_map but boost can't serialize it, really there is no way how to do it? No one had similar problem ever?

**Comment by donovanhide** [comment]
You need to write a custom (de)serializer. Have a look at these docs:

https://cdn.rawgit.com/sparsehash/sparsehash/master/doc/sparse_hash_map.html#io

**Comment by MitchesD** [comment]
That's what I already did, but I have tons of errors due to that vector, for example: http://paste2.org/3Kww0EnW
and it's not problem of my serializer, it works on normal std::unordered_map, that's why I am asking for some other solution (btw, it does these errors even when serializer does nothing, and ONLY during reading)

**Comment by donovanhide** [comment]
Well, post your serialization code :-)

**Comment by MitchesD** [comment]
http://paste2.org/2BJd5bvB Read is now just for testing, but it does errors even when I read it to local variables or even when I read nothing..

**Comment by donovanhide** [comment]
You'll need to provide a full reproducible and compilable piece of code if you want help debugging.

**Comment by MitchesD** [comment]
Okay, http://paste2.org/E6bP2HhM this is code for test

**Comment by donovanhide** [comment]
That didn't compile :-)

I think maybe the funky placement new here might have been tripping you up. This seems to work without error:

https://gist.github.com/donovanhide/d1960ea00d4ac1406364ea22d23df6e7#file-gistfile1-txt-L38

**Comment by MitchesD** [comment]
thank you so much, it works ;)
