### ISSUE TITLE
sparse_hash_map<string, int> Serializer/Unserializer

### ISSUE THREAD

**Issue by haggins** [sparsehash/sparsehash#124]
Hi,

this might be a stupid question because I've got not too much C++ experience.

I try to serialize and unserialize a `sparse_hash_map<string, int>`. While the serialization seems to be ok, I can't get the unserialize method working.

Here's the example:
https://gist.github.com/haggins/1302ee09bb63ad8c772e0d7080fcd5b7

And this is the error:

> /home/haggis/ClionProjects/demo/main.cpp: In member function ‘bool StringToIntSerializer::operator()(std::ifstream*, std::pair<const std::basic_string<char>, int>*) const’:
> /home/haggis/ClionProjects/demo/main.cpp:24:47: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
>          new (&value->first) string(first, size);
>                                                ^
> In file included from /usr/include/c++/4.8/ext/new_allocator.h:33:0,
>                  from /usr/include/x86_64-linux-gnu/c++/4.8/bits/c++allocator.h:33,
>                  from /usr/include/c++/4.8/bits/allocator.h:46,
>                  from /usr/include/c++/4.8/string:41,
>                  from /usr/include/c++/4.8/bits/locale_classes.h:40,
>                  from /usr/include/c++/4.8/bits/ios_base.h:41,
>                  from /usr/include/c++/4.8/ios:42,
>                  from /usr/include/c++/4.8/ostream:38,
>                  from /usr/include/c++/4.8/iostream:39,
>                  from /home/haggis/ClionProjects/demo/main.cpp:1:
> /usr/include/c++/4.8/new:109:14: error:   initializing argument 2 of ‘void* operator new(std::size_t, void*)’ [-fpermissive]
>  inline void* operator new(std::size_t, void* __p) _GLIBCXX_USE_NOEXCEPT

I got inspired by the docs, [another gist](https://gist.github.com/donovanhide/d1960ea00d4ac1406364ea22d23df6e7) and [this question](https://groups.google.com/forum/#!topic/google-sparsehash/oSqJqPyWmDE).

Any hints?

Thank you
haggins

**Comment by Dekken** [comment]
Please have a look at the comments on https://github.com/sparsehash/sparsehash/issues/121

**Comment by haggins** [comment]
Thank you @Dekken 
The solution of that issue was to use `new(&item->second) std::vector<Test>(first);`. However, in my case I need to change the value of the first element of the pair, which must be const.
I tried it with `new (&value->first) string(first, size);` but had no luck (see my gist).

How is the first element at #121 within the unserializer modified? Seems like they don't touch it at all.

**Comment by greg7mdp** [comment]
use : new (const_cast<string *>(&value->first)) string(first, size); 

also: stream->write(value.first.c_str(), sizeFirst);

I have updated your gist to make it work.

**Comment by Dekken** [comment]
@haggins reopen if you require
