### ISSUE TITLE
incorrect result printout for time_hash_map

### ISSUE THREAD

**Issue by greg7mdp** [sparsehash/sparsehash#125]
The number of copies is incorrect, as it is not reset when the real test begins. Code should be in time_hash_map.cc:342

inline void Rusage::Reset() {
    g_num_copies = 0;
    g_num_hashes = 0;

**Comment by donovanhide** [comment]
Patch welcome :-)

**Comment by greg7mdp** [comment]
Will do.

**Comment by donovanhide** [comment]
Fixed in d6684b241c915a2764caa20270e48d9c5f25eb1d
