### ISSUE TITLE
test code biased

### ISSUE THREAD

**Issue by greg7mdp** [sparsehash/sparsehash#126]
I think the lines below should be removed from time_hash_map.cc. 

1. because they cause the sparse_hash tables to use memcpy, the reported number for num_copies when running time_hash_map is incorrect. 
2. this is an untypical case where hash map entries would be large and have trivial copy/destructor, So when when testing with large (256 byte keys), the test with this optimization makes the sparse_hash look better than it 
3. Finally, even when entries do have trivial copy/destructor, users are unlikely to know to define these traits.

template<int Size, int Hashsize>
struct has_trivial_copy< HashObject<Size, Hashsize> > : true_type { };

template<int Size, int Hashsize>
struct has_trivial_destructor< HashObject<Size, Hashsize> > : true_type { };

**Comment by donovanhide** [comment]
Not sure why you wouldn't want to be able to make sparsehash run as fast as possible :-) If you want to extend the benchmark to cover both cases, patches welcome :-)

Also bear in mind that this has been simplified in the C++11 version:

https://github.com/sparsehash/sparsehash-c11/blob/master/sparsehash/traits#L34-L55

**Comment by greg7mdp** [comment]
Well, it does make the benchmark misleading, because the benchmark (for 256 byte entries) spends all its time doing copies, and focuses on an untypical case (plain old data) and a non-default optimization hack.
I think it would be OK to have this optimization, but the benchmark should also include more typical cases (for example when the key or values contain a std::string).
I'll be happy to submit a patch.

**Comment by greg7mdp** [comment]
I am closing the issue. I still think that specifying a custom trait in the benchmark to allow an internal optimization makes the result a little bit misleading, but I guess I can understand the desire to make the sparsehash look as good as possible.

**Comment by donovanhide** [comment]
Fixed in 90e60f03d03323ee225009c10c3fbb8864e23282

Regarding traits for relocation magic, sparsehash isn't the only data structure in town to use such tricks:

https://github.com/facebook/folly/blob/master/folly/docs/Traits.md
https://github.com/facebook/folly/blob/master/folly/docs/FBVector.md#object-relocation

**Comment by greg7mdp** [comment]
Yes, I had seen this trick in Folly. I actually like the IsRelocatable name much better than those used in Google's sparsehash, and in my own version I have implemented is_relocatable, which means that the object can be memcopied to another place in memory without making it incorrect, which is the case of most objects, even those with non-trivial constructors and destructors. However, std::string in g++ 5.0 is not relocatable, which was an error reported for Folly because they assumed it was (see https://github.com/facebook/folly/issues/316)
