### ISSUE TITLE
Collision algorithm

### ISSUE THREAD

**Issue by saru95** [sparsehash/sparsehash#136]
I'm studying Google's SparshHash for a personal project. I've understood that it uses binary strings and sparse table for memory efficiency. However, I'm unable to find the hashing function that it uses and the algorithm it uses for collision handling. Could I be briefed on that ?

I'm a newbie. So, sorry for the naive question. Thanks !

**Comment by donovanhide** [comment]
Hi,

collision choices are detailed here:
https://github.com/sparsehash/sparsehash/blob/master/src/sparsehash/internal/sparsehashtable.h#L32-L93
and the hash function is settable in the template parameters:
https://github.com/sparsehash/sparsehash/blob/master/src/sparsehash/dense_hash_map#L186
and, I believe, defaults to std::hash:
http://en.cppreference.com/w/cpp/utility/hash
which will have specializations for the hashmap key type.

**Comment by saru95** [comment]
Oh ! Thanks !

**Comment by saru95** [comment]
If you don't mind could you help me on the following issue.

Which files do I need to focus on if I need to port `dense_hash_map` to C ? Thanks.

**Comment by Dekken** [comment]
I imagine [this](https://github.com/sparsehash/sparsehash/blob/master/src/sparsehash/internal/densehashtable.h) and [this](https://github.com/sparsehash/sparsehash/blob/master/src/sparsehash/internal/hashtable-common.h)
