### ISSUE TITLE
problem with make install in macOS Sierra

### ISSUE THREAD

**Issue by raqxavier** [sparsehash/sparsehash#138]
God evening

I am trying to install sparsehash, /.configure runs OK, and so does make, but when I try make install there is a fatal error: 

install: /usr/local/share/doc/sparsehash-2.0.2/AUTHORS: Permission denied
make[2]: *** [install-dist_docDATA] Error 71
make[1]: *** [install-am] Error 2
make: *** [install] Error 2

Can someone help please?

**Comment by Dekken** [comment]
Try

'''
./configure
make
sudo make install
'''

either that or login as root and run without sudo

>

**Comment by raqxavier** [comment]
Thanks that seems to work, but i when I want to install ea-utils, i still get an error:
fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 warnings and 20 errors generated.
make[2]: *** [hashtable_test.o] Error 1
make[1]: *** [all] Error 2
make: *** [sparsehash] Error 2

**Comment by Dekken** [comment]
That is not much to work with, please create a build log as a [public [gist](https://gist.github.com/raqxavier) and link the file.

**Comment by raqxavier** [comment]
Dekken thank you for your help in advanced!


[gistfile1.txt](https://github.com/sparsehash/sparsehash/files/702845/gistfile1.txt)

**Comment by Dekken** [comment]
I recall some issues with gcc on OSX, do you have clang installed or could upgrade gcc?

**Comment by raqxavier** [comment]
Dekken i will try those options and let you know how it goes!

thanks again

**Comment by raqxavier** [comment]
Hi Dekken

I upgraded gcc and resolved the issue. I am still getting problems with ea-utils as I get an error in make install. i trying to work around that at the moment I think my gsl installation did not properly.

thanks for your help
Raquel

**Comment by vickysharma0812** [comment]
I am getting error at the first step 

```
h147:sparsehash vikas$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/Users/vikas/Documents/sparsehash':
configure: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

**Comment by Dekken** [comment]
```C++ compiled programs````

Usually means your PATH / LD_LIBRARY_PATH are misconfigured.
