### ISSUE TITLE
google::dense_hash_map <string, int> m_wordCount is failed when m_wordCount[str] += 1; on running time

### ISSUE THREAD

**Issue by muhammetp** [sparsehash/sparsehash#140]
google::dense_hash_map <string, int> m_wordCount is failed when m_wordCount[str] += 1; on running time code is compiled but when it runs it fails and the error on command line is  
Assertion `settings.use_empty()' failed.
Aborted (core dumped)

**Comment by muhammetp** [comment]
any sample for dense_hash_map <string, int>  to increase value wrt its key

**Comment by Dekken** [comment]
have you called "set_empty_key" ?

**Comment by muhammetp** [comment]
thank you so much for reply. i fix thıs




________________________________
