### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by Timmmm** [sparsehash/sparsehash#148]
Reasons:

* CMake is probably the most common C++ build system these days.
* Although still quite insane, it is far far less insane than Autotools.
* It's much easier to read.
* Supports IDEs
* Doesn't make the source tree dirty (running `./configure` seems to modify `configure` itself, and create `autom4te.cache`.

**Comment by Dekken** [comment]
perhaps try the C++11 version?

https://github.com/sparsehash/sparsehash-c11/

**Comment by Timmmm** [comment]
Ah didn't know about that - will do! You should add a link to it in the readme.
