### ISSUE TITLE
macOS 10.13.6 installation: cannot run C++ compiled programs

### ISSUE THREAD

**Issue by mdozmorov** [sparsehash/sparsehash#151]
Hello,

Running `./configure` fails with "configure: error: cannot run C++ compiled programs." A bigger picture - I'm trying to compile [ea-utils](https://github.com/ExpressionAnalysis/ea-utils/blob/wiki/Compiling.md), which fails with the same error. 

The detailed output of `./configure` is:

````
checking whether make sets $(MAKE)... yes
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/Users/mdozmorov/Documents/nobackup/ea-utils/clipper/sparsehash':
configure: error: cannot run C++ compiled programs.
````

And the full `config.log` is attached.

Thanks for your help,
Mikhail
[config.log](https://github.com/sparsehash/sparsehash/files/3056784/config.log)

**Comment by Dekken** [comment]
https://github.com/ExpressionAnalysis/ea-utils/issues/75 

you could try this to see if it works for you

**Comment by mdozmorov** [comment]
The [sparsehash-c11](https://github.com/sparsehash/sparsehash-c11) version doesn't have the `configure` file. When I just try running `make`, it still errors:

````
<... lots of outputs skipped ...>
      testing::internal::UniversalTersePrinter<wchar_t const*>::Print(wchar_t const*, std::__1::basic_ostream<char, std::__1::char_traits<char> >*) in gmock-gtest-all.o
  "_write", referenced from:
      testing::internal::DeathTestImpl::Abort(testing::internal::DeathTest::AbortReason) in gmock-gtest-all.o
ld: symbol(s) not found for architecture x86_64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:46: sparsehash_unittests] Error 1
````

I'm not very familiar with C code structure and compiling, so not sure where to go from here...

**Comment by Dekken** [comment]
https://github.com/sparsehash/sparsehash-c11 is header only - there is no configure required.

make is just compiling the tests, which it looks like you're having trouble with a system call with

**Comment by Dekken** [comment]
are you positive your compiler is not misconfigured in some way?

**Comment by mdozmorov** [comment]
Not sure what may be misconfigured. The system is rather fresh. I've been googling, finding some suggestions about "LD_LIBRARY_PATH" variable (empty in my case), but not sure where to go from there. My configuration files are rather simple: [dotfiles](https://github.com/mdozmorov/dotfiles). 

And, some info about `gcc` and `g++`:

````(base) MacBook-Pro-4:dotfiles mdozmorov$ which gcc
/usr/bin/gcc
(base) MacBook-Pro-4:dotfiles mdozmorov$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(base) MacBook-Pro-4:dotfiles mdozmorov$ which g++
/usr/bin/g++
(base) MacBook-Pro-4:dotfiles mdozmorov$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
(base) MacBook-Pro-4:dotfiles mdozmorov$
````

Anything obviously misconfigured?

**Comment by Dekken** [comment]
https://travis-ci.org/mkn/google.sparsehash/jobs/517842961 looks all ok here with OSX 10.2 and CLANG 7

**Comment by mdozmorov** [comment]
I was following https://embeddedartistry.com/blog/2017/2/20/installing-clangllvm-on-osx. After setting the path and the flags in a terminal session as recommended, I can run `make` on https://github.com/sparsehash/sparsehash-c11 without errors.

Not sure what to do next to compile `sparsehash` itself.

**Comment by Dekken** [comment]
did you try "./configure" after setting the flags/etc?

**Comment by mdozmorov** [comment]
Compiling after setting the environment as described https://embeddedartistry.com/blog/2017/2/20/installing-clangllvm-on-osx worked! So, after running `make` for https://github.com/sparsehash/sparsehash-c11, I could `./configure`, `make` and `make install` for https://github.com/sparsehash/sparsehash. 

As of the bigger picture, `ea-utils` partially compiled with these setting. Most of the tools can now be run as binaries. One error ('samtools/sam.h' file not found with <angled> include; use "quotes" instead), but that is a different story and issue.

Thank you, @Dekken, for quick help with this.
