### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by mboisson** [sparsehash/sparsehash#157]
Hi,
I am hitting the error
```
void* realloc(void*, size_t) moving an object of non-trivially  copyable type struct std::pair<const std::__cxx11::basic_string<char>, short unsigned int>; use new and delete instead [-Werror=class-memaccess]
``` 

i.e. https://github.com/sparsehash/sparsehash/issues/149

However, I'm running the latest release of SparseHash. Is there any way to make a new release that includes these recent fixes ?

**Comment by Dekken** [comment]
I'll do this soonish

**Comment by Dekken** [comment]
done

 https://github.com/sparsehash/sparsehash/releases/tag/sparsehash-2.0.4
