### ISSUE TITLE
when i try to complie it in vs2015 it show this error

### ISSUE THREAD

**Issue by 0nyoun9** [sparsehash/sparsehash#169]
错误	C2084	函数“int snprintf(char *const ,const std::size_t,const char *const ,...)”已有主体	type_traits_unittest	c:\users\ms\downloads\sparsehash-master2\sparsehash-master\src\windows\port.cc	44	
i want to konw how to install it in windows.open sparsehash.sln in vs ?and complie and run it?i have read readme_windows

**Comment by PhilipDeegan** [comment]
Using sparsehash only requires the headers
unless you want to build all the tests too
